### ISSUE TITLE
Feedback for First Model/Views

### ISSUE THREAD

**Issue by oobbles** [oobbles/06-23-fania#14]
This is for the Artist Class.  View only supports listing of Artist and finding associated albums for that artist.  Artist.rb contains methods to do other things, but my plan is to only allow the user to enter a full album entry (album, year, artist(s) and style(s)) not individual artists.

**Comment by sumeetjain** [comment]
- Indentation
  - [x] https://github.com/oobbles/06-23-fania/blob/master/database_class_methods.rb
  - [x] Close tags on their own line to avoid indentation issues caused by [this](https://github.com/oobbles/06-23-fania/blob/master/views/artists/list_artists.erb#L10)
- [x] [Documentation](https://github.com/oobbles/06-23-fania/blob/master/models/artist.rb#L8-L12) needs to reflect that the method takes a Hash.
- [x] Documentation doesn't need to conform to TomDoc necessarily, but it needs _some_ consistent format. Knowing where in a comment to look for argument descriptions, type of object being returned, etc, is helpful. Your documentation is usually correct, but it requires reading the entire comment to get any single piece of information. If you want to invent your own format, I'm cool with it – but please then follow that format exactly in all your method documentation.

**Comment by oobbles** [comment]
Sumeet Jain [11:01 AM] 
@oobbles: :thumbsup: :rocket:
